import type { NodeField, WorkflowNodeType } from "./types"
import {
  aiPromptField,
  aiModelField,
  aiTemperatureField,
  databaseOperationField,
  databaseQueryField,
  databaseTableField,
} from "./ai-db-fields"
import {
  emailBodyField,
  emailCcField,
  emailSubjectField,
  emailToField,
  formIdField,
} from "./email-form-fields"
import {
  httpBodyField,
  httpBodyTypeField,
  httpHeadersField,
  httpMethodField,
  httpQueryField,
  httpRedirectsField,
  httpResponseTypeField,
  httpTimeoutField,
  httpUrlField,
} from "./http-fields"
import { logicGateNodes } from "./logic-nodes"
import { codeTransformNodes } from "./code-transform-nodes"
import {
  pollIntervalField,
  rssFields,
  scheduleFields,
  webhookFields,
} from "./trigger-fields"
import { notifyFileNodes } from "./notify-file-nodes"
import {
  ACTION_EXECUTION,
  HTTP_EXECUTION,
  LOGIC_EXECUTION,
  aiChatOutputs,
  aiClassifyOutputs,
  aiExtractOutputs,
  aiGenerationOutputs,
  appEventOutputs,
  callOutputs,
  databaseQueryOutputs,
  databaseRowOutputs,
  downloadFileOutputs,
  emailInboundOutputs,
  emailOutboundOutputs,
  fileEventOutputs,
  fileWriteOutputs,
  formTriggerOutputs,
  formatterOutputs,
  httpRequestOutputs,
  manualOutputs,
  notificationActionOutputs,
  notificationEventOutputs,
  pollUrlOutputs,
  rssOutputs,
  scheduleOutputs,
  switchOutputs,
  webhookOutputs,
} from "./io-contracts"

function credentialField(help?: string): NodeField {
  return {
    key: "credentialId",
    label: "Credential",
    placeholder: "None",
    control: "credential",
    section: "connection",
    mode: "fixed",
    help: help ?? "Saved connection used for this step.",
  }
}

function method(
  id: string,
  kind: "trigger" | "action",
  label: string,
  description: string,
  fields: NodeField[],
  extra: Pick<
    WorkflowNodeType,
    "outputs" | "inputs" | "executionOptions" | "testable" | "ports"
  >
): WorkflowNodeType {
  return {
    id,
    label,
    description,
    kind,
    category: kind === "trigger" ? "Triggers" : "Apps",
    fields,
    outputs: extra.outputs,
    inputs: extra.inputs,
    executionOptions: extra.executionOptions,
    testable: extra.testable,
    ports: extra.ports,
  }
}

const emailFilterFields = (): NodeField[] => [
  credentialField("Mailbox account used to watch mail."),
  {
    key: "mailbox",
    label: "Mailbox",
    placeholder: "INBOX",
    section: "parameters",
    mode: "either",
  },
  {
    key: "folder",
    label: "Folder",
    placeholder: "Inbox",
    section: "parameters",
    mode: "either",
  },
  { key: "from", label: "From contains", placeholder: "@acme.com", section: "options", mode: "either" },
  { key: "to", label: "To contains", placeholder: "ops@acme.com", section: "options", mode: "either" },
  { key: "cc", label: "Cc contains", placeholder: "", section: "options", mode: "either" },
  { key: "subject", label: "Subject contains", placeholder: "", section: "options", mode: "either" },
  { key: "bodyContains", label: "Body contains", placeholder: "", section: "options", mode: "either" },
  {
    key: "unreadOnly",
    label: "Unread only",
    placeholder: "false",
    control: "boolean",
    section: "options",
    mode: "fixed",
  },
  {
    key: "hasAttachment",
    label: "Has attachment",
    placeholder: "false",
    control: "boolean",
    section: "options",
    mode: "fixed",
  },
  {
    key: "pollFallback",
    label: "Poll if push is unavailable",
    placeholder: "true",
    control: "boolean",
    section: "options",
    mode: "fixed",
  },
]

export const platformNodes: WorkflowNodeType[] = [
  {
    id: "manual",
    label: "Manual",
    description: "Start this workflow by hand.",
    kind: "trigger",
    category: "Triggers",
    fields: [
      {
        key: "examplePayload",
        label: "Example payload",
        placeholder: '{ "ok": true }',
        control: "code",
        language: "json",
        section: "options",
        validation: [{ kind: "json" }],
        help: "Optional sample payload shown in Out before a run.",
      },
      {
        key: "exampleSchema",
        label: "Example schema",
        placeholder: "",
        control: "schema",
        section: "options",
      },
    ],
    outputs: manualOutputs,
    testable: true,
  },
  {
    id: "webhook",
    label: "Webhook",
    description: "Start when an HTTP request arrives.",
    kind: "trigger",
    category: "Triggers",
    fields: webhookFields(),
    outputs: webhookOutputs,
    testable: true,
  },
  {
    id: "schedule",
    label: "Schedule",
    description: "Run on a cron expression or a repeating interval.",
    kind: "trigger",
    category: "Triggers",
    fields: scheduleFields(),
    outputs: scheduleOutputs,
  },
  {
    id: "email",
    label: "Email received",
    description: "Start when a matching email arrives.",
    kind: "trigger",
    category: "Triggers",
    fields: emailFilterFields(),
    outputs: emailInboundOutputs,
  },
  {
    id: "form",
    label: "Form submitted",
    description: "Start when a form is submitted.",
    kind: "trigger",
    category: "Triggers",
    fields: [
      credentialField(),
      formIdField(),
      { key: "status", label: "Status filter", placeholder: "completed", section: "options", mode: "either" },
    ],
    outputs: formTriggerOutputs,
  },
  {
    id: "app-event",
    label: "App event",
    description: "Start when something happens in a connected app.",
    kind: "trigger",
    category: "Triggers",
    fields: [
      credentialField(),
      { key: "app", label: "App", placeholder: "Sheets", section: "parameters", mode: "fixed", required: true },
      { key: "event", label: "Event", placeholder: "New row", section: "parameters", mode: "fixed", required: true },
      { key: "filters", label: "Event filters", placeholder: "", control: "keyValue", section: "options", mode: "either" },
    ],
    outputs: appEventOutputs,
  },
  {
    id: "rss",
    label: "RSS",
    description: "Start when an RSS or Atom feed has a new item.",
    kind: "trigger",
    category: "Triggers",
    fields: rssFields(),
    outputs: rssOutputs,
  },
  {
    id: "inbound-call",
    label: "Inbound call",
    description: "Start when a phone call is received.",
    kind: "trigger",
    category: "Triggers",
    fields: [
      credentialField(),
      { key: "number", label: "Number", placeholder: "+1 555 0100", help: "The number or queue that should start this workflow.", section: "parameters", mode: "either" },
      { key: "route", label: "Route", placeholder: "support", help: "Optional IVR or routing key.", section: "options", mode: "either" },
      {
        key: "status",
        label: "Status",
        placeholder: "completed",
        control: "select",
        section: "options",
        mode: "fixed",
        options: [
          { value: "ringing", label: "Ringing" },
          { value: "in-progress", label: "In progress" },
          { value: "completed", label: "Completed" },
          { value: "busy", label: "Busy" },
          { value: "no-answer", label: "No answer" },
        ],
      },
      { key: "record", label: "Record", placeholder: "false", control: "boolean", section: "options", mode: "fixed" },
      { key: "transcribe", label: "Transcribe", placeholder: "false", control: "boolean", section: "options", mode: "fixed" },
    ],
    outputs: callOutputs,
  },
  {
    id: "outbound-call",
    label: "Outbound call",
    description: "Start when an outbound call is placed.",
    kind: "trigger",
    category: "Triggers",
    fields: [
      credentialField(),
      { key: "to", label: "To", placeholder: "+1 555 0199", help: "Destination number that triggers the workflow.", section: "parameters", mode: "either" },
      { key: "from", label: "From", placeholder: "+1 555 0100", section: "parameters", mode: "either" },
      { key: "record", label: "Record", placeholder: "false", control: "boolean", section: "options", mode: "fixed" },
      { key: "transcribe", label: "Transcribe", placeholder: "false", control: "boolean", section: "options", mode: "fixed" },
    ],
    outputs: callOutputs,
  },
  {
    id: "http",
    label: "HTTP Request",
    description: "Call any REST API.",
    kind: "action",
    category: "Actions",
    fields: [
      httpMethodField("GET"),
      httpUrlField("https://api.example.com"),
      httpQueryField(),
      httpHeadersField(),
      httpBodyTypeField(),
      httpBodyField(),
      httpTimeoutField(),
      httpRedirectsField(),
      httpResponseTypeField(),
    ],
    outputs: httpRequestOutputs,
    executionOptions: [...HTTP_EXECUTION],
    testable: true,
  },
  {
    id: "email-send",
    label: "Send email",
    description: "Send an email message.",
    kind: "action",
    category: "Actions",
    fields: [
      credentialField(),
      emailToField("team@example.com"),
      emailCcField(),
      {
        key: "bcc",
        label: "Bcc",
        placeholder: "audit@example.com",
        section: "parameters",
        mode: "either",
        validation: [{ kind: "email" }],
        help: "One or more email addresses, separated by commas.",
      },
      {
        key: "replyTo",
        label: "Reply-To",
        placeholder: "noreply@example.com",
        section: "options",
        mode: "either",
        validation: [{ kind: "email" }],
      },
      {
        key: "from",
        label: "From",
        placeholder: "Vanteg <ops@example.com>",
        section: "options",
        mode: "either",
      },
      emailSubjectField("Update"),
      emailBodyField("Thanks, we got it."),
      {
        key: "html",
        label: "HTML body",
        placeholder: "<p>Thanks</p>",
        control: "textarea",
        section: "options",
        mode: "either",
      },
      {
        key: "attachments",
        label: "Attachments",
        placeholder: "/tmp/file.pdf",
        section: "options",
        mode: "either",
      },
    ],
    outputs: emailOutboundOutputs,
    executionOptions: [...ACTION_EXECUTION],
  },
  ...notifyFileNodes,
  {
    id: "ai",
    label: "AI",
    description: "Send a prompt to an AI model.",
    kind: "action",
    category: "Actions",
    fields: [
      credentialField(),
      {
        key: "provider",
        label: "Provider",
        placeholder: "xai",
        control: "select",
        section: "connection",
        mode: "fixed",
        options: [
          { value: "xai", label: "xAI" },
          { value: "openai", label: "OpenAI" },
          { value: "anthropic", label: "Anthropic" },
          { value: "google", label: "Google" },
        ],
      },
      {
        key: "system",
        label: "System prompt",
        placeholder: "You are a helpful assistant.",
        control: "textarea",
        section: "parameters",
        mode: "either",
      },
      aiPromptField("Summarize the input"),
      aiModelField(),
      aiTemperatureField(),
      {
        key: "maxOutput",
        label: "Max output tokens",
        placeholder: "1024",
        control: "number",
        section: "options",
        validation: [{ kind: "integer" }, { kind: "min", value: 1 }],
      },
      {
        key: "responseFormat",
        label: "Response format",
        placeholder: "text",
        control: "select",
        section: "options",
        mode: "fixed",
        options: [
          { value: "text", label: "Text" },
          { value: "json", label: "JSON" },
        ],
      },
      {
        key: "timeout",
        label: "Timeout (ms)",
        placeholder: "60000",
        control: "number",
        section: "options",
        validation: [{ kind: "integer" }, { kind: "min", value: 1 }],
      },
    ],
    outputs: aiGenerationOutputs,
    executionOptions: [...ACTION_EXECUTION],
    testable: true,
  },
  method("http-poll", "trigger", "Poll URL", "Start when an HTTP endpoint changes.", [
    httpMethodField("GET"),
    httpUrlField("https://api.example.com/status"),
    httpQueryField(),
    httpHeadersField(),
    pollIntervalField(),
    {
      key: "compareMode",
      label: "Compare",
      placeholder: "body",
      control: "select",
      section: "options",
      mode: "fixed",
      options: [
        { value: "body", label: "Whole body" },
        { value: "path", label: "JSON path" },
        { value: "hash", label: "Hash" },
      ],
    },
    {
      key: "comparePath",
      label: "Compare path",
      placeholder: "status",
      section: "options",
      mode: "either",
      showWhen: { key: "compareMode", equals: "path" },
    },
    {
      key: "emitFirst",
      label: "Emit on first check",
      placeholder: "false",
      control: "boolean",
      section: "options",
      mode: "fixed",
    },
    {
      key: "dedupe",
      label: "Dedupe",
      placeholder: "true",
      control: "boolean",
      section: "options",
      mode: "fixed",
    },
  ], { outputs: pollUrlOutputs }),
  method("http-download", "action", "Download file", "Download a file over HTTP.", [
    httpUrlField("https://example.com/file.csv"),
    httpHeadersField(),
    { key: "path", label: "Save as", placeholder: "/tmp/file.csv", section: "parameters", mode: "either" },
    httpTimeoutField(),
    httpRedirectsField(),
  ], { outputs: downloadFileOutputs, executionOptions: [...HTTP_EXECUTION] }),
  method("email-new-attachment", "trigger", "New attachment", "Start when an email with an attachment arrives.", [
    ...emailFilterFields().map((field) =>
      field.key === "hasAttachment" ? { ...field, placeholder: "true", defaultValue: "true" } : field
    ),
  ], { outputs: emailInboundOutputs }),
  method("email-reply", "action", "Reply to email", "Reply to an inbound email.", [
    credentialField(),
    { key: "messageId", label: "Message ID", placeholder: "{{Email received.messageId}}", section: "parameters", mode: "expression", required: true },
    { key: "threadId", label: "Thread ID", placeholder: "{{Email received.threadId}}", section: "parameters", mode: "expression" },
    emailToField("ada@acme.com"),
    emailCcField(),
    emailSubjectField("Re: Update"),
    emailBodyField("Thanks, we got it."),
    { key: "attachments", label: "Attachments", placeholder: "", section: "options", mode: "either" },
  ], { outputs: emailOutboundOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("email-forward", "action", "Forward email", "Forward an inbound email.", [
    credentialField(),
    { key: "messageId", label: "Message ID", placeholder: "{{Email received.messageId}}", section: "parameters", mode: "expression", required: true },
    emailToField("ops@acme.com"),
    emailCcField(),
    emailSubjectField("Fwd: Update"),
    emailBodyField("Routing to ops.", "Note"),
  ], { outputs: emailOutboundOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("database-new-row", "trigger", "New row", "Start when a database row is inserted.", [
    credentialField(),
    { key: "table", label: "Table", placeholder: "jobs", section: "parameters", required: true, mode: "either" },
    { key: "filter", label: "Filter", placeholder: "", section: "options", mode: "either" },
  ], { outputs: databaseRowOutputs }),
  method("database-row-updated", "trigger", "Row updated", "Start when a database row changes.", [
    credentialField(),
    { key: "table", label: "Table", placeholder: "jobs", section: "parameters", required: true, mode: "either" },
    { key: "filter", label: "Filter", placeholder: "", section: "options", mode: "either" },
  ], { outputs: databaseRowOutputs }),
  {
    id: "database",
    label: "Query rows",
    description: "Read or write database rows.",
    kind: "action",
    category: "Apps",
    fields: [
      credentialField(),
      databaseOperationField("insert"),
      databaseTableField("jobs"),
      databaseQueryField(),
      {
        key: "values",
        label: "Values",
        placeholder: "",
        control: "mapping",
        section: "parameters",
        mode: "either",
        showWhen: { key: "operation", equals: ["insert", "update"] },
      },
      {
        key: "limit",
        label: "Limit",
        placeholder: "100",
        control: "number",
        section: "options",
        showWhen: { key: "operation", equals: "select" },
        validation: [{ kind: "integer" }, { kind: "min", value: 1 }],
      },
    ],
    outputs: databaseQueryOutputs,
    executionOptions: [...ACTION_EXECUTION],
  },
  method("database-insert-row", "action", "Insert row", "Insert a database row.", [
    credentialField(),
    { key: "table", label: "Table", placeholder: "jobs", required: true, mode: "either" },
    { key: "values", label: "Values", placeholder: "status=open", control: "mapping", mode: "either" },
  ], { outputs: databaseQueryOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("database-update-row", "action", "Update row", "Update a database row.", [
    credentialField(),
    { key: "table", label: "Table", placeholder: "jobs", required: true, mode: "either" },
    { key: "id", label: "Row ID", placeholder: "42", required: true, mode: "either" },
    { key: "values", label: "Values", placeholder: "", control: "mapping", mode: "either" },
  ], { outputs: databaseQueryOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("database-delete-row", "action", "Delete row", "Delete a database row.", [
    credentialField(),
    { key: "table", label: "Table", placeholder: "jobs", required: true, mode: "either" },
    { key: "id", label: "Row ID", placeholder: "42", required: true, mode: "either", validation: [{ kind: "destructive" }] },
  ], { outputs: databaseQueryOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("ai-chat-received", "trigger", "Chat message received", "Start when a chat message is sent to the model.", [
    credentialField(),
    { key: "channel", label: "Channel", placeholder: "support", section: "parameters", mode: "either" },
  ], { outputs: aiChatOutputs }),
  method("ai-generation-finished", "trigger", "Generation finished", "Start when an AI generation completes.", [
    credentialField(),
    { key: "model", label: "Model", placeholder: "grok-4", section: "parameters", mode: "either" },
  ], { outputs: aiGenerationOutputs }),
  method("ai-generation-failed", "trigger", "Generation failed", "Start when an AI generation errors.", [
    credentialField(),
    { key: "model", label: "Model", placeholder: "grok-4", section: "parameters", mode: "either" },
  ], { outputs: aiGenerationOutputs }),
  method("ai-classify", "action", "Classify", "Classify text with an AI model.", [
    credentialField(),
    {
      key: "system",
      label: "System prompt",
      placeholder: "Classify the text.",
      control: "textarea",
      section: "parameters",
      mode: "either",
    },
    aiPromptField("The invoice is overdue"),
    { key: "labels", label: "Labels", placeholder: "urgent, billing, spam", section: "parameters", mode: "either", required: true },
    { key: "multilabel", label: "Multi-label", placeholder: "false", control: "boolean", section: "options", mode: "fixed" },
    { key: "minConfidence", label: "Min confidence", placeholder: "0.5", control: "number", section: "options", validation: [{ kind: "min", value: 0 }, { kind: "max", value: 1 }] },
    { key: "fallbackLabel", label: "Fallback label", placeholder: "other", section: "options", mode: "either" },
    aiModelField(),
    aiTemperatureField(),
    { key: "timeout", label: "Timeout (ms)", placeholder: "60000", control: "number", section: "options", validation: [{ kind: "integer" }] },
  ], { outputs: aiClassifyOutputs, executionOptions: [...ACTION_EXECUTION], testable: true }),
  method("ai-extract", "action", "Extract", "Extract structured fields from text.", [
    credentialField(),
    {
      key: "system",
      label: "System prompt",
      placeholder: "Extract the fields.",
      control: "textarea",
      section: "parameters",
      mode: "either",
    },
    aiPromptField("Ada Lovelace, ada@acme.com"),
    { key: "schema", label: "Fields", placeholder: "name, email", control: "schema", section: "parameters" },
    aiModelField(),
    aiTemperatureField(),
    { key: "timeout", label: "Timeout (ms)", placeholder: "60000", control: "number", section: "options", validation: [{ kind: "integer" }] },
  ], { outputs: aiExtractOutputs, executionOptions: [...ACTION_EXECUTION], testable: true }),
  method("file-created", "trigger", "File created", "Start when a file is created.", [
    credentialField(),
    { key: "path", label: "Path", placeholder: "/tmp/inbox", required: true, mode: "either" },
    { key: "pattern", label: "Pattern", placeholder: "*", section: "options", mode: "either" },
  ], { outputs: fileEventOutputs }),
  method("file-updated", "trigger", "File updated", "Start when a file changes.", [
    credentialField(),
    { key: "path", label: "Path", placeholder: "/tmp/export.csv", required: true, mode: "either" },
  ], { outputs: fileEventOutputs }),
  method("file-deleted", "trigger", "File deleted", "Start when a file is deleted.", [
    credentialField(),
    { key: "path", label: "Path", placeholder: "/tmp/inbox", required: true, mode: "either" },
  ], { outputs: fileEventOutputs }),
  method("file-delete", "action", "Delete file", "Delete a file.", [
    { key: "path", label: "Path", placeholder: "/tmp/export.csv", required: true, mode: "either", validation: [{ kind: "destructive" }] },
    {
      key: "ifMissing",
      label: "If missing",
      placeholder: "error",
      control: "select",
      section: "options",
      mode: "fixed",
      options: [
        { value: "error", label: "Error" },
        { value: "skip", label: "Skip" },
      ],
    },
  ], { outputs: fileWriteOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("file-copy", "action", "Copy file", "Copy a file to a new path.", [
    { key: "from", label: "From", placeholder: "/tmp/export.csv", required: true, mode: "either" },
    { key: "to", label: "To", placeholder: "/tmp/archive/export.csv", required: true, mode: "either" },
    { key: "overwrite", label: "Overwrite", placeholder: "true", control: "boolean", section: "options", mode: "fixed" },
  ], { outputs: fileWriteOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("file-move", "action", "Move file", "Move a file to a new path.", [
    { key: "from", label: "From", placeholder: "/tmp/export.csv", required: true, mode: "either" },
    { key: "to", label: "To", placeholder: "/tmp/archive/export.csv", required: true, mode: "either" },
    { key: "overwrite", label: "Overwrite", placeholder: "true", control: "boolean", section: "options", mode: "fixed" },
  ], { outputs: fileWriteOutputs, executionOptions: [...ACTION_EXECUTION] }),
  method("notification-received", "trigger", "Notification received", "Start when an in-app notification arrives.", [
    credentialField(),
    { key: "channel", label: "Channel", placeholder: "ops", section: "parameters", mode: "either" },
  ], { outputs: notificationEventOutputs }),
  method("notification-clicked", "trigger", "Notification clicked", "Start when a notification is opened.", [
    credentialField(),
    { key: "channel", label: "Channel", placeholder: "ops", section: "parameters", mode: "either" },
  ], { outputs: notificationEventOutputs }),
  method("notification-broadcast", "action", "Broadcast", "Send a notification to a group.", [
    credentialField(),
    { key: "audience", label: "Audience", placeholder: "ops-oncall", required: true, mode: "either" },
    { key: "title", label: "Title", placeholder: "Incident opened", required: true, mode: "either" },
    { key: "message", label: "Message", placeholder: "", control: "textarea", mode: "either" },
  ], { outputs: notificationActionOutputs, executionOptions: [...ACTION_EXECUTION] }),
  ...logicGateNodes,
  ...codeTransformNodes,
  {
    id: "paths",
    label: "Paths",
    description: "Branch into multiple conditional paths.",
    kind: "logic",
    category: "Logic",
    fields: [
      { key: "field", label: "Field", placeholder: "status", control: "expression", section: "parameters", mode: "expression" },
      {
        key: "routes",
        label: "Paths",
        placeholder: '[{"id":"a","name":"won","value":"won"}]',
        control: "routes",
        section: "parameters",
        validation: [{ kind: "uniqueRouteName" }],
        help: "Named paths with stable IDs. The workflow continues on the first matching path.",
      },
    ],
    outputs: switchOutputs,
    ports: [
      { id: "in", type: "target", label: "In", color: "slate" },
      { id: "default", type: "source", label: "Default", color: "amber" },
    ],
    dynamicPorts: {
      fieldKey: "routes",
      type: "source",
      fallbackPorts: [
        { id: "a", type: "source", label: "A", color: "violet" },
        { id: "b", type: "source", label: "B", color: "sky" },
        { id: "default", type: "source", label: "Default", color: "amber" },
      ],
    },
    executionOptions: [...LOGIC_EXECUTION],
  },
  {
    id: "formatter",
    label: "Formatter",
    description: "Transform text, numbers, or dates between steps.",
    kind: "logic",
    category: "Logic",
    fields: [
      {
        key: "operation",
        label: "Operation",
        placeholder: "text",
        control: "select",
        section: "parameters",
        mode: "fixed",
        options: [
          { value: "text", label: "Text" },
          { value: "number", label: "Number" },
          { value: "date", label: "Date & Time" },
          { value: "boolean", label: "Boolean" },
          { value: "array", label: "Array" },
          { value: "object", label: "Object" },
          { value: "encoding", label: "Encoding" },
        ],
      },
      { key: "input", label: "Value", placeholder: "{{Webhook.body}}", control: "expression", section: "parameters", mode: "expression" },
      {
        key: "textOp",
        label: "Text operation",
        placeholder: "trim",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "text" },
        options: [
          { value: "trim", label: "Trim" },
          { value: "upper", label: "Uppercase" },
          { value: "lower", label: "Lowercase" },
          { value: "replace", label: "Replace" },
        ],
      },
      {
        key: "numberOp",
        label: "Number operation",
        placeholder: "round",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "number" },
        options: [
          { value: "round", label: "Round" },
          { value: "floor", label: "Floor" },
          { value: "ceil", label: "Ceil" },
          { value: "format", label: "Format" },
        ],
      },
      {
        key: "dateOp",
        label: "Date operation",
        placeholder: "format",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "date" },
        options: [
          { value: "format", label: "Format" },
          { value: "add", label: "Add" },
          { value: "timezone", label: "Convert timezone" },
        ],
      },
      {
        key: "booleanOp",
        label: "Boolean operation",
        placeholder: "toBoolean",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "boolean" },
        options: [
          { value: "toBoolean", label: "To boolean" },
          { value: "not", label: "Not" },
          { value: "toString", label: "To string" },
        ],
      },
      {
        key: "arrayOp",
        label: "Array operation",
        placeholder: "join",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "array" },
        options: [
          { value: "join", label: "Join" },
          { value: "first", label: "First" },
          { value: "last", label: "Last" },
          { value: "length", label: "Length" },
          { value: "unique", label: "Unique" },
        ],
      },
      {
        key: "objectOp",
        label: "Object operation",
        placeholder: "keys",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "object" },
        options: [
          { value: "keys", label: "Keys" },
          { value: "values", label: "Values" },
          { value: "pick", label: "Pick" },
          { value: "omit", label: "Omit" },
        ],
      },
      {
        key: "encodingOp",
        label: "Encoding operation",
        placeholder: "base64",
        control: "select",
        section: "parameters",
        showWhen: { key: "operation", equals: "encoding" },
        options: [
          { value: "base64", label: "Base64 encode" },
          { value: "base64decode", label: "Base64 decode" },
          { value: "url", label: "URL encode" },
          { value: "urldecode", label: "URL decode" },
          { value: "hex", label: "Hex encode" },
        ],
      },
      {
        key: "format",
        label: "Format",
        placeholder: "yyyy-MM-dd",
        section: "parameters",
        mode: "either",
        showWhen: { key: "operation", equals: ["date", "number"] },
      },
      {
        key: "argument",
        label: "Argument",
        placeholder: "",
        section: "parameters",
        mode: "either",
        showWhen: { key: "operation", equals: ["text", "array", "object", "date"] },
        help: "Separator, search/replace text, keys, or duration depending on the operation.",
      },
    ],
    outputs: formatterOutputs,
    executionOptions: [...LOGIC_EXECUTION],
  },
]
