import type { LucideIcon } from "lucide-react"
import {
  Bell,
  BookOpen,
  ClipboardList,
  Building2,
  Calendar,
  Clock,
  Code,
  CreditCard,
  Database,
  File,
  Filter,
  GitBranch,
  GitPullRequest,
  Globe,
  Grid3x3,
  Hash,
  Inbox,
  Merge,
  MessageCircle,
  Pencil,
  PhoneIncoming,
  PhoneOutgoing,
  Play,
  Repeat,
  Reply,
  Rss,
  Send,
  Shuffle,
  Sparkles,
  Split,
  Table,
  Ticket,
  Timer,
  Webhook,
} from "lucide-react"

const icons: Record<string, LucideIcon> = {
  manual: Play,
  webhook: Webhook,
  schedule: Clock,
  email: Inbox,
  form: ClipboardList,
  "app-event": Bell,
  rss: Rss,
  "inbound-call": PhoneIncoming,
  "outbound-call": PhoneOutgoing,
  http: Globe,
  "email-send": Send,
  notification: Bell,
  file: File,
  "respond-webhook": Reply,
  ai: Sparkles,
  slack: Hash,
  spreadsheet: Table,
  google: Table,
  database: Database,
  github: GitPullRequest,
  notion: BookOpen,
  airtable: Grid3x3,
  discord: MessageCircle,
  if: GitBranch,
  switch: Split,
  filter: Filter,
  delay: Timer,
  code: Code,
  set: Pencil,
  merge: Merge,
  loop: Repeat,
  transform: Shuffle,
  paths: Split,
  formatter: Pencil,
  hubspot: Building2,
  salesforce: Building2,
  pipedrive: Building2,
  attio: Building2,
  "zoho-crm": Building2,
  stripe: CreditCard,
  paypal: CreditCard,
  square: CreditCard,
  calendar: Calendar,
  "google-calendar": Calendar,
  "outlook-calendar": Calendar,
  "google-forms": ClipboardList,
  "google-docs": File,
  typeform: ClipboardList,
  surveymonkey: ClipboardList,
  zendesk: Ticket,
  intercom: Ticket,
  front: Ticket,
  "help-scout": Ticket,
}

export function NodeIcon({
  catalogId,
  className,
}: {
  catalogId: string
  className?: string
}) {
  const Icon =
    icons[catalogId] ??
    icons[catalogId.split("-")[0] ?? ""] ??
    Sparkles
  return <Icon className={className} />
}
